name: Build and Test.

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    
    env: 
      BUILD_CONFIG_MODE: Release

    steps:
      - name: Checkout.
        uses: actions/checkout@v3
        
      - name: Setup .NET.
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: Restore dependencies.
        run: dotnet restore

      - name: Build.
        run: dotnet build --no-restore --configuration $BUILD_CONFIG_MODE

      - name: Test.
        run: dotnet test --no-build --verbosity normal