name: Deploy to NuGet and Release section.

on:
  push: 
    tags:
      - "v*"

permissions:
  contents: write # For release creation.

env:
  BUILD_MODE: Release
  PROJECT_PATH: 'src/MikesSifter/MikesSifter.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
        
jobs: 
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout.
        uses: actions/checkout@v4
        
      - name: Get package version.
        run: |
          Import-Module ./scripts/GetPackageVersion.psm1
          Write-Host "Github ref: $Env:GITHUB_REF"
          $version = GetVersionFromGitHubRef -GitHubRef $Env:GITHUB_REF
          
          Write-Host "Extracted version: '$version'"
          
          if ($version -eq $null) {
            Write-Error "Package version not found."
            exit 1
          }
          
          echo "PACKAGE_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh
        
      - name: Install .NET.
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Restore dependencies.
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build.
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration ${{ env.BUILD_MODE }}
        
      - name: Pack.
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration ${{ env.BUILD_MODE }} --include-symbols -p:PackageVersion=${{ env.PACKAGE_VERSION }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: Push to Nuget.
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s ${{ env.NUGET_SOURCE_URL }}
        
      - name: Create release.
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true